# # -*- coding: utf-8 -*-
# """DQN.ipynb

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/12BZ1G2DjoDbuJz2eEVEQolTwR_8IaILz
# """

# import os

# def installWrapper():
#     # Install a Drive FUSE wrapper.
#     # https://github.com/astrada/google-drive-ocamlfuse
#     !apt-get update -qq 2>&1 > /dev/null
#     !apt-get install -y -qq software-properties-common python-software-properties module-init-tools
#     !add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
#     !apt-get update -qq 2>&1 > /dev/null
#     !apt-get -y install -qq google-drive-ocamlfuse fuse
    
# def auth():
#     from google.colab import auth
#     auth.authenticate_user()
    
# def authorizeWrapper():
#     # Generate creds for the Drive FUSE library.
#     from google.colab import output
#     from oauth2client.client import GoogleCredentials
#     import time
#     creds = GoogleCredentials.get_application_default()
#     import getpass
#     # Determine if Drive Fuse credential setup is already complete.
#     fuse_credentials_configured = False
#     with output.temporary():
#       !google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1
#       # _exit_code is set to the result of the last "!" command.
#       fuse_credentials_configured = _exit_code == 0
#     # Sleep for a short period to ensure that the previous output has been cleared.
#     time.sleep(1)
#     if fuse_credentials_configured:
#       print('Drive FUSE credentials already configured!')
#     else:
#       # Work around misordering of STREAM and STDIN in Jupyter.
#       # https://github.com/jupyter/notebook/issues/3159
#       prompt = !google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
#       vcode = getpass.getpass(prompt[0] + '\n\nEnter verification code: ')
#       !echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}
    
# def createDriveDir():
#     !mkdir -p drive
#     !google-drive-ocamlfuse drive
    
# installWrapper()
# auth()
# authorizeWrapper()
# createDriveDir()





import pickle


def savePickle(name, toSave):
    file = open(name, 'wb')
    pickle.dump(toSave, file)
    file.close()

def loadPickle(name):
    file = open(name, 'rb')
    data = pickle.load(file)
    file.close()
    return data

import random
import gym
import numpy as np
from collections import deque
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import sgd,Adam
from itertools import product as possibleIterations
import matplotlib.pyplot as plt


def get_actions():
    possibleTorques = np.array([-1.0, 0.0, 1.0])
    possibleActions = np.array(
        list(possibleIterations(possibleTorques, possibleTorques, possibleTorques, possibleTorques)))
    return possibleActions


EPISODES = 100000
actions_space = get_actions()

def plot(data):
    x=[]
    y=[]
    for i,j in data:
        x.append(i)
        y.append(j)
    plt.plot(x,y)
    plt.savefig('temp.png')

class State:
    def __init__(self, states, actions):
        self.states = states# 4 sattes
        self.actions = actions # 3 actions

    def get_input_layer(self):
        ret = []
        for i in range(3):
            ret = ret + list(self.states[i][0])
            ret.append(actions_space.tolist().index(self.actions[i].tolist()))
        ret = ret + list(self.states[3][0])
        ret = np.array(ret)
        ret = np.reshape(ret, [1, 24*4 + 3])

        return ret



class DeepQAgent:
    def __init__(self, state_size, action_space):
        self.state_size = state_size
        self.action_size = 81
        self.memory = deque(maxlen=20000)
        self.gamma = 0.95
        self.epsilon = 1.0
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.999
        self.learning_rate = 0.005
        self.model = self._build_model()
        self.action_space = action_space

    def get_action_from_prediction(self, predict):
        return self.action_space[np.argmax(predict[0])]

    def _build_model(self):
        model = Sequential()
        model.add(Dense(100, input_dim=self.state_size, activation='relu'))  # changed layer count from 24
        model.add(Dense(80, activation='relu'))
        model.add(Dense(self.action_size, activation='relu'))  # changed this from linear
        model.compile(loss='mse', optimizer=Adam(lr=self.learning_rate))
        return model

    def remember(self, state, action, reward, next_state, done):
        action_index = self.action_space.tolist().index(action.tolist())
        self.memory.append((state, action_index, reward, next_state, done))

    def act(self, state):
        if np.random.rand() <= self.epsilon:
            return self.action_space[np.random.choice([i for i in range(len(self.action_space))])]
        act_values = self.model.predict(state.get_input_layer())  # what does this return
        return self.get_action_from_prediction(act_values)

    def replay(self, batch_size, agent2):
        minibatch = random.sample(self.memory, batch_size)
        for state, action, reward, next_state, done in minibatch:
            target = reward
            target_t = self.model.predict(next_state.get_input_layer())
            target_f = self.model.predict(state.get_input_layer())
            if not done:
                target = 0.01 * (reward + self.gamma * target_t[0][action] - target_f[0][action])  # Returns q-values
            target_f[0][action] = target
            self.model.fit(state.get_input_layer(), target_f, epochs=1, verbose=0)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

    def load(self, name, mName):
        #self.memory = loadPickle(mName)
        self.model.load_weights(name)

    def save(self, name, mName):
        savePickle(mName,self.memory)
        self.model.save_weights(name)
        


if __name__ == "__main__":
    eVSs = deque(maxlen=1000)
    env = gym.make('BipedalWalker-v2')
    state_size = env.observation_space.shape[0]
    action_size = len(actions_space)
    agent1 = DeepQAgent(state_size*4 + 3, actions_space)
    agent2 = DeepQAgent(state_size*4 + 3, actions_space)
    #agent1.load("agent1.h5",'memory1')
    #agent2.load("agent2.h5",'memory2')
    done = False
    batch_size = 32
    e = 0
    #e = loadPickle('iter')
    #e, eVSs = e
    recent_average = deque(maxlen=100)
    while True:
        e=e+1
        state = env.reset()
        state = np.reshape(state, [1, state_size])
        total_reward = 0
        prev_state = State([state for i in range(4)], [np.array([-1.0, 0.0, 1.0, 1.0]) for i in range(3)])
        curr_state = State([state for i in range(4)], [np.array([-1.0, 0.0, 1.0, 1.0]) for i in range(3)])
        my_state = deque(maxlen=4)
        my_actions = deque(maxlen=3)
        my_state.append(state)
        flag = True
        for time in range(500):
            #c += 1
            # env.render()
            action = agent1.act(curr_state)
            my_actions.append(action)

            next_state, reward, done, _ = env.step(action)
            total_reward += reward
            next_state = np.reshape(next_state, [1, state_size])
            state = next_state
            my_state.append(state)

            if done:
                break

            if len(my_state) == 4:
                curr_state = State(my_state, my_actions)
                if flag:
                    prev_state = curr_state
                    flag = False
                agent1.remember(prev_state, action, reward, curr_state, done)
                prev_state = curr_state

            if len(agent1.memory) > batch_size :
                agent1.replay(batch_size, agent2)
            #if c >= 1000:
                #print('updating model')
                #c = 0
                #agent2.model.set_weights(agent.model.get_weights())
        recent_average.append(total_reward)
        av = sum(recent_average) / len(recent_average)
        print("episode: {}/{}, score: {} ,Recent Average: {}".format(e, EPISODES, total_reward, av))
        eVSs.append((e+1,av))
        if e % 20 == 0:
            agent1.save("agent1.h5",'memory1')
            #agent2.save("agent2.h5",'memory2')
            savePickle('iter',(e, eVSs))
            plot(eVSs)





# !ls

# os.chdir('gym')

# !ls

# !pip install -e .

# !pip install -e .[box2D]

# os.chdir('..')

# !ls

# !rm -rf gym

# !ls

# !pip uninstall gym

# !pip install gym

# !git clone https://github.com/openai/gym

# import gym



